version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "qba73"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "qba73"
  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: weekly
    reviewers:
      - "qba73"
